version: "{build}"

environment:
  GITHUB_TAG_NAME: v$(APPVEYOR_BUILD_VERSION)
  matrix:
    - JAVA_VERSION: "8"
      JAVA_HOME: C:\Program Files\Java\jdk1.8.0
      _JAVA_OPTIONS: "-Dtestfx.robot=awt"

shallow_clone: true

build_script:
  - mvn clean install -DskipTests

test_script:
  - mvn test -B

before_build:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/set-screenresolution.ps1'))
  - ps: Set-ScreenResolution 1920 1080

artifacts:
  - path: alica-plan-designer-fx-controller\target\PlanDesigner-*.jar
    name: App

deploy:
  - provider: GitHub
    auth_token:
      secure: gC8oWOphLjwUFQfByUJQ/sS+LGl4xBUhOkORvwUIb1mrstwWRAHaidskrSOLnHhF
    artifact: App
    tag: $(GITHUB_TAG_NAME)
    release: $(GITHUB_TAG_NAME)
    description: ''
    draft: false
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: true

#after_build:
#  - ps: Get-ChildItem .\alica-plan-designer-fx-controller\target\PlanDesigner-*.jar | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

notifications:
  - provider: Slack
    auth_token:
      secure: 6fgzuwD9QHg2w6I1Q9cVPwSH6ZXt4gcSLSMFkglW0bVA4NhTHNPPyHj6lTrt+dFYpQw0WvXEMuY4BXCPf68hlLJr8duS4Qwzn5zc/DONxIM=
    channel: '#alica-plan-designer-fx'
    on_build_success: true  # TODO: set to false later

#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
