version: "{branch} {build}"

environment:
  matrix:
    - JAVA_VERSION: "8"
      JAVA_HOME: C:\Program Files\Java\jdk1.8.0
      _JAVA_OPTIONS: "-Dtestfx.robot=awt"

shallow_clone: true

build_script:
  - mvn clean install -DskipTests

test_script:
  - mvn test -B

init:
  - ps: $screen_resolution = '1400x900'; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
