version: "{build}"

environment:
  matrix:
    - JAVA_VERSION: "11"
      JAVA_HOME: C:\Program Files\Java\jdk11
      _JAVA_OPTIONS: "-Dtestfx.robot=awt"

# fetch repository as zip archive
shallow_clone: true

# install without run tests
build_script:
  - mvn clean install -DskipTests

# run tests
test_script:
  - mvn test -B

# increase screen size
before_build:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/set-screenresolution.ps1'))
  - ps: Set-ScreenResolution 1920 1080

# build cache
cache:
  - C:\maven\ -> appveyor.yml
  - C:\Users\appveyor\.m2\ -> **\pom.xml

# files that will be uploaded
artifacts:
  - path: alica-plan-designer-fx-controller\target\PlanDesigner-*.jar

deploy:
  # github artifact upload to tag/release
  - provider: GitHub
    auth_token:
      secure: /GqIUIFjaJtRIncBGDG7Ws2lkrEDnaOncyh6Nt4i9EQJ4DHWlvyywQt2PEWsREd1
    force_update: true
    on:
      branch: master
      APPVEYOR_REPO_TAG: true

notifications:
  # slack notification
  - provider: Slack
    auth_token:
      secure: 6fgzuwD9QHg2w6I1Q9cVPwSH6ZXt4gcSLSMFkglW0bVA4NhTHNPPyHj6lTrt+dFYpQw0WvXEMuY4BXCPf68hlLJr8duS4Qwzn5zc/DONxIM=
    channel: '#alica-plan-designer-fx'
    on_build_success: true  # TODO: set to false later

#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
